### ISSUE TITLE
'U_SPIFFS' was not declared in this scope

### ISSUE THREAD

**Issue by carlosm9272** [lbernstone/asyncUpdate#4]
Hi,
Thanks a lot for your code and contribution! - Just a little comment from my side, when compile for ESP8266 board there is an error due to a difference between updater.h and update.h, "'U_SPIFFS' was not declared in this scope".  Possibly the only change it needs is the segregation bewteen U_FS and U_SPIFFS:
	`#ifdef ESP8266
	    int cmd = (filename.indexOf("spiffs") > -1) ? U_FS  : U_FLASH;
	#else
	    int cmd = (filename.indexOf("spiffs") > -1) ? U_SPIFFS : U_FLASH;
	#endif`

**Comment by anthonysleck** [comment]
As stated above, comment out line 42 and add the differentiation of the ESP32 and the ESP8266 updaters like below. It works perfectly. Thanks.

//int cmd = (filename.indexOf("spiffs") > -1) ? U_SPIFFS : U_FLASH;
    #ifdef ESP8266
    int cmd = (filename.indexOf("spiffs") > -1) ? U_FS : U_FLASH;
    #else int
    cmd = (filename.indexOf("spiffs") > -1) ? U_SPIFFS : U_FLASH;
    #endif
