### ISSUE TITLE
In function 'boolean webInit()':   error: no return statement in function returning non-void

### ISSUE THREAD

**Issue by DarekLin** [lbernstone/asyncUpdate#5]
Hi,
Thanks for sharing this useful sketch, but I have a slight problem with compiling it.
When trying to compile a sketch in arduino IDE for esp32, I get a comile error:

In function 'boolean webInit()':   error: no return statement in function returning non-void [-Werror=return-type]

**Comment by lbernstone** [comment]
I'm sure I had some intention with that... Just throw a return true at the end of the webInit function.
