### ISSUE TITLE
How to stop the mdns service

### ISSUE THREAD

**Issue by Manu-dewa** [lbernstone/asyncUpdate#7]
is there a way to stop the mdns service from running. i saw your AsyncUpdate.ino code what is the mechanism to start the service and stop the service. i am noob in this area and there is no much help in explanation in the web

Thank you

**Comment by lbernstone** [comment]
MDNS.end(), but if you don't want it, then just don't call the begin in setup.  asyncUpdate does not rely on mdns, it is just a handy tool so you don't need to know the ip address of the server.
