### ISSUE TITLE
How to upload files into SPIFF with asyncUpdate?

### ISSUE THREAD

**Issue by 1973byJuan** [lbernstone/asyncUpdate#8]
Dear Ibernstone,

First of all thank you for sharing the sketch to use ESPAsyncWebServer to update ESP8266 and ESP32 sketch. Really use full!!!!
I have been able to update the sketch of my ESP8266 through Web. Reading the code it looks that it is supported to update files in the SPIFF partition, but I don't know what is the structure of the file that I shall to use for it.
Please, could you kindly support on it?

Thank you in advanced,
BR
Juan

**Comment by lbernstone** [comment]
Sorry for the delayed response.
You can use [mkspiffs](https://github.com/igrr/mkspiffs) from the command line to manually build a spiffs.bin file, or use the [plugin](https://github.com/esp8266/arduino-esp8266fs-plugin) and put the files into a "data" folder under your sketch directory.  When you install the plugin, get it working through the usb connection first.  Then, if you choose to upload the spiffs with no connection, you will get an error, but the file will be created in a temporary directory (not exactly sure where this ends up in windows, but maybe %TEMP%/arduino_build_xxx).  You should be able to search your drive for "*.spiffs.bin" to find it.
